# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('company_number', models.CharField(max_length=100)),
                ('business_sector', models.CharField(choices=[(b'retail', b'Retail'), (b'professional services', b'Professional Services'), (b'food & drink', b'Food & Drink'), (b'entertainment', b'Entertainment')], max_length=100)),
                ('borrowing', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('days', models.CharField(max_length=100)),
                ('reason_for_loan', models.CharField(max_length=2000)),
            ],
        ),
    ]
