# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='borrowing',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='days',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(max_length=15),
        ),
    ]
