# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170313_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='borrowing',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
